using System.Text.Json;

namespace GoalMaker.Core.Design;

/// <summary>
/// The GoalMaker mark as contracts/design/logo.json draws it (generated by tools/generate_app_icon.py):
/// a tile <paramref name="Size"/> units wide with <paramref name="TileCorner"/> corners, the G
/// (<paramref name="Letter"/>, stroked), and the trend line (<paramref name="Trend"/>, stroked) with its
/// <paramref name="Head"/> (filled). Strokes are <paramref name="Stroke"/> wide; paths are SVG path data.
/// </summary>
public sealed record LogoMark(double Size, double TileCorner, double Stroke, string Letter, string Trend, string Head)
{
    public static LogoMark Load(Stream json)
    {
        using var document = JsonDocument.Parse(json);
        var root = document.RootElement;
        return new LogoMark(
            root.GetProperty("size").GetDouble(),
            root.GetProperty("tileCorner").GetDouble(),
            root.GetProperty("stroke").GetDouble(),
            root.GetProperty("letter").GetString()!,
            root.GetProperty("trend").GetString()!,
            root.GetProperty("head").GetString()!);
    }
}
