package com.goalmaker.app.domain.design

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.float
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * The GoalMaker mark as contracts/design/logo.json draws it (generated by tools/generate_app_icon.py):
 * a tile [size] units wide with [tileCorner] corners, the G ([letter], stroked), and the trend line
 * ([trend], stroked) with its [head] (filled). Strokes are [stroke] wide; paths are SVG path data.
 */
data class LogoMark(
    val size: Float,
    val tileCorner: Float,
    val stroke: Float,
    val letter: String,
    val trend: String,
    val head: String,
) {
    companion object {
        fun parse(json: String): LogoMark {
            val root = Json.parseToJsonElement(json).jsonObject
            fun text(name: String) = root.getValue(name).jsonPrimitive.content
            fun number(name: String) = root.getValue(name).jsonPrimitive.float
            return LogoMark(number("size"), number("tileCorner"), number("stroke"), text("letter"), text("trend"), text("head"))
        }
    }
}
